repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282 # Use the latest stable version of ruff
    hooks:
      - id: ruff
        args: ["--select=I", "--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest stable version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
