services:
  client:
    container_name: client
    hostname: client
    build:
      context: client/.
    env_file:
      - ./client/.env.docker
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

  server:
    container_name: server
    hostname: server
    build:
      context: server/.
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env.docker
    networks:
      - app-network
    depends_on:
      - promptfoo-server
      - mongo

  promptfoo-server:
    container_name: promptfoo-server
    hostname: promptfoo-server
    build:
      context: promptfoo-server/.
    ports:
      - "8080:8080"
    env_file:
      - ./promptfoo-server/.env
    networks:
      - app-network

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
