###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import pprint
from typing import (
    Any,
    Dict,
    List,
    Literal,
    Optional,
    Type,
    TypedDict,
    TypeVar,
    Union,
    cast,
)

import baml_py
from pydantic import BaseModel, ValidationError, create_model
from typing_extensions import NotRequired

from . import partial_types, types
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
)
from .type_builder import TypeBuilder
from .types import Check, Checked

OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client



    async def GeneratePromptMessages(
        self,
        params: types.GenParams,
        baml_options: BamlCallOptions = {},
    ) -> List[types.GenPromptMessage]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "GeneratePromptMessages",
        {
          "params": params,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.GenPromptMessage], raw.cast_to(types, types))

    async def GenerateTestCases(
        self,
        params: types.GenParams,
        baml_options: BamlCallOptions = {},
    ) -> List[types.GenTestCase]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "GenerateTestCases",
        {
          "params": params,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.GenTestCase], raw.cast_to(types, types))



class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager


    def GeneratePromptMessages(
        self,
        params: types.GenParams,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.GenPromptMessage], List[types.GenPromptMessage]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "GeneratePromptMessages",
        {
          "params": params,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.GenPromptMessage], List[types.GenPromptMessage]](
        raw,
        lambda x: cast(List[partial_types.GenPromptMessage], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.GenPromptMessage], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )

    def GenerateTestCases(
        self,
        params: types.GenParams,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.GenTestCase], List[types.GenTestCase]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "GenerateTestCases",
        {
          "params": params,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.GenTestCase], List[types.GenTestCase]](
        raw,
        lambda x: cast(List[partial_types.GenTestCase], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.GenTestCase], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )


b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]
