import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Box from "@mui/material/Box"
import { Providers, SessionLoaded } from "@/components"
import { ThemeProvider } from "@mui/material"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SessionLoaded>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                backgroundColor: "#F3F2F7",
                paddingX: "4rem",
                paddingY: "1rem",
                height: "100%",
                width: "100%",
                overflowY: "auto",
              }}
            >
              {children}
            </Box>
          </SessionLoaded>
        </Providers>
      </body>
    </html>
  )
}
